# Generated by Django 3.1.7 on 2021-03-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_articlepost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepost',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d'),
        ),
    ]
